import Roles from "./roles";

const house = [
  {
    label: "Roses farm house",
    value: 1,
    address: "221B Baker Street, London, England",
    rooms: 4,
    members: [{ name: "Anna" }, { name: "bob" }],
    role: Roles.OWNER,
  },
  {
    label: "Roses farm house",
    value: 2,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
    ],
    role: Roles.OWNER,
  },
  {
    label: "Roses farm house",
    value: 3,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [{ name: "Anna" }, { name: "bob" }],
    role: Roles.OWNER,
  },
  {
    label: "Roses farm house",
    value: 4,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
    ],
    role: Roles.GUEST,
  },
  {
    label: "Roses farm house",
    value: 5,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [{ name: "Anna" }, { name: "bob" }],
    role: Roles.GUEST,
  },
  {
    label: "Roses farm house",
    value: 6,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
    ],
    role: Roles.GUEST,
  },
  {
    label: "Roses farm house",
    value: 7,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [{ name: "Anna" }, { name: "bob" }],
    role: Roles.GUEST,
  },
  {
    label: "Roses farm house",
    value: 8,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
    ],
    role: Roles.GUEST,
  },
  {
    label: "Roses farm house",
    value: 9,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [{ name: "Anna" }, { name: "bob" }],
    role: Roles.GUEST,
  },
  {
    label: "Roses farm house",
    value: 10,
    address: "221B Baker Street, London, England",
    rooms: 7,
    members: [
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
      { name: "Anna" },
      { name: "bob" },
    ],
    role: Roles.GUEST,
  },
];

export default house;
